# Solutions to Assignment 2


### 1. Create a numpy array with 10 elements of the shape(10,1) using np.random and find out the mean of the elements using basic numpy functions.

In [1]:
import numpy as np

In [2]:
##Create numpy array
array = np.random.rand(10,1)

In [3]:
print (array)

[[ 0.44755504]
 [ 0.03195737]
 [ 0.84541872]
 [ 0.56687559]
 [ 0.43799034]
 [ 0.10063683]
 [ 0.31099462]
 [ 0.25262361]
 [ 0.49082538]
 [ 0.70747429]]


In [4]:
##Find mean and print value
print(array.mean())

0.419235179528


### 2. Create a numpy array with 20 elements of the shape(20,1) using np.random  find the variance and standard deviation of the elements.


In [5]:
##Create numpy array
array = np.random.rand(20,1)
array

array([[ 0.66350383],
       [ 0.41588268],
       [ 0.22658189],
       [ 0.45428465],
       [ 0.92762679],
       [ 0.95884851],
       [ 0.10809027],
       [ 0.91365145],
       [ 0.58632468],
       [ 0.56571219],
       [ 0.33125951],
       [ 0.72725255],
       [ 0.40233334],
       [ 0.76284125],
       [ 0.29374283],
       [ 0.53148146],
       [ 0.83714089],
       [ 0.27428337],
       [ 0.71764915],
       [ 0.46209006]])

In [6]:
#Variance
variance = array.std()

#Standard Deviation
standard_deviation = (array - array.mean())/variance

In [7]:
#Print the values
print('Variance : {} \n\nStandard Deviation :\n {}'.format(variance, standard_deviation))

Variance : 0.243811538 

Standard Deviation :
 [[ 0.43260774]
 [-0.58301746]
 [-1.35944007]
 [-0.42551068]
 [ 1.51591563]
 [ 1.64397241]
 [-1.84543687]
 [ 1.45859539]
 [ 0.11605526]
 [ 0.03151254]
 [-0.93010181]
 [ 0.69407496]
 [-0.63859049]
 [ 0.84004302]
 [-1.08397758]
 [-0.10888579]
 [ 1.14478512]
 [-1.16379109]
 [ 0.65468634]
 [-0.39349656]]


### 3.Create a numpy array A of shape(10,20) and B of shape (20,25) using np.random. Print the matrix which is the matrix multiplication of A and B. The shape of the new matrix should be (10,25). Using basic numpy math functions only find the sum of all the elements of the new matrix.


In [8]:
##Create arrays A and B
A = np.random.rand(10,20)
B = np.random.rand(20, 25)

In [9]:
##Perform matrix multiplication using np.matmul
matrix_mul = np.matmul(A,B)

In [10]:
print (matrix_mul)

[[ 5.11832426  5.24858784  5.17696395  4.75059187  3.15755809  5.60295853
   4.08230752  5.29167852  4.15226889  4.42894882  4.74771476  4.81433307
   5.06788893  4.63380134  3.99228705  4.98629219  5.55927108  4.35574979
   4.193556    4.06539528  5.32374799  4.36030723  3.43488434  3.75118949
   5.24617768]
 [ 5.08989678  5.39966004  6.5927278   5.28852981  4.01191987  5.36579605
   5.21022738  5.78260952  4.59323816  5.27665384  4.33748249  4.97544942
   5.58535177  4.61225703  4.27032182  5.69806679  6.27074965  4.69396144
   4.00587535  5.04701677  5.10870739  5.31182236  4.78805726  4.01868073
   5.55400489]
 [ 4.46008168  4.87967946  6.07833379  5.03742939  2.96139681  5.14102859
   3.49658118  4.98032946  3.52550792  4.86970125  4.69820935  4.48867497
   5.10871876  4.47454773  3.84478105  4.5336781   5.5241455   3.63575186
   3.65686074  4.24064615  5.613915    3.97980823  3.98501998  3.54592181
   3.9806024 ]
 [ 5.80718981  6.4159225   7.24641291  6.32596401  4.57122913  6.62

In [11]:
##Check the shape of the matrix
matrix_mul.shape

(10L, 25L)

In [12]:
##Sum of all elements
sum_m = matrix_mul.sum() 

##Print sum
print sum_m

1299.333145


### 4.Create a numpy array A of shape(10,1).Using the basic operations of the numpy array generate an array of shape(10,1) such that each element is the following function applied on each element of A.

### f(x)=1 / (1 + exp(-x)) 
### Apply this function to each element of A and print the new array holding the value the function returns

Ex.
a=[a1,a2,a3]   
n(new array to be printed )=[ f(a1), f(a2), f(a3)]


In [13]:
##Create numpy array A
A = np.random.rand(10,1)
print A

[[ 0.05946117]
 [ 0.78458076]
 [ 0.49227511]
 [ 0.02754604]
 [ 0.18800825]
 [ 0.03439194]
 [ 0.04794942]
 [ 0.86754315]
 [ 0.25069869]
 [ 0.56917188]]


In [14]:
## Define the function to be applied
def func(x):
    return (1 / (1 + np.exp(-x)))

In [15]:
##Apply the function on A
result = np.apply_along_axis(func, 0, A)

In [ ]:
##Print result
print (result)

[[ 0.51486092]
 [ 0.68666653]
 [ 0.62064224]
 [ 0.50688608]
 [ 0.5468641 ]
 [ 0.50859714]
 [ 0.51198506]
 [ 0.70423422]
 [ 0.56234846]
 [ 0.63857207]]
